config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save
    redirect_to flats_path
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :price_per_night, :number_of_guests, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<h1>All our Flats (<%= @flats.count %>)</h1>

<div class="row justify-content-between">
  <% @flats.each do |flat| %>
    <div class="col-md-4">
      <div class="border rounded p-3 my-3">
        <h4><%= flat.name %></h4>
        <p><%= flat.address %></p>
        <div class="d-flex">
          <div class= "d-flex me-2">
            <i class="fas fa-user-friends"></i>
            <p><%= flat.number_of_guests %></p>
          </div>
          <div class= "d-flex">
            <i class="fas fa-dollar-sign"></i>
            <p><%= flat.price_per_night %></p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/flats/new.html.erb
<div class="row">
  <div class="col-6 m-auto">
    <div class="form">
      <h1>Add a new Flat</h1>
      <%= simple_form_for @flat do |f| %>
        <%= f.input :name %>
        <%= f.input :address %>
        <%= f.input :description %>
        <%= f.input :number_of_guests %>
        <%= f.input :price_per_night %>

        <%= f.submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar p-3 mb-3">
      <%= link_to 'Simple Airbnb', flats_path, class: "text-decoration-none" %>
      <%= link_to 'Add Flat', new_flat_path, class: "btn btn-primary" %>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>